import resend

from core.config import RESEND_API_KEY, EMAIL_SENDER
from core.models import Itinerary


def _build_html(itinerary: Itinerary, routes: dict) -> str:
    days_html = ""
    for day in itinerary.days:
        day_route = routes.get(day.day_number)
        rows = ""
        total_visit = 0
        total_drive = 0

        for i, attr in enumerate(day.attractions):
            rows += f"""
            <tr>
              <td style="padding:6px 12px;white-space:nowrap;">{attr.time}</td>
              <td style="padding:6px 12px;">{attr.place}</td>
              <td style="padding:6px 12px;white-space:nowrap;">{attr.duration_min} min</td>
            </tr>"""
            total_visit += attr.duration_min

            if day_route and i < len(day.attractions) - 1:
                leg = day_route["legs"][i]
                drive_min = round(leg["duration_s"] / 60)
                drive_km  = leg["distance_m"] / 1000
                total_drive += drive_min
                rows += f"""
            <tr>
              <td colspan="3" style="padding:2px 12px;color:#888;font-size:12px;">
                🚗 &nbsp;{drive_min} min &nbsp;·&nbsp; {drive_km:.1f} km
              </td>
            </tr>"""

        drive_note = (
            f" &nbsp;+&nbsp; 🚗 {total_drive} min driving (additional)" if total_drive else ""
        )
        days_html += f"""
        <h3 style="margin:28px 0 4px;color:#1e293b;">
          Day {day.day_number} &nbsp;·&nbsp; {day.date} &nbsp;·&nbsp; {day.title}
        </h3>
        <p style="margin:0 0 10px;color:#64748b;font-size:14px;">{day.description}</p>
        <table style="border-collapse:collapse;width:100%;font-size:14px;">
          <thead>
            <tr style="background:#f1f5f9;">
              <th style="padding:6px 12px;text-align:left;">Time</th>
              <th style="padding:6px 12px;text-align:left;">Place</th>
              <th style="padding:6px 12px;text-align:left;">Duration</th>
            </tr>
          </thead>
          <tbody>{rows}</tbody>
        </table>
        <p style="margin:8px 0 0;font-size:13px;color:#475569;">
          ⏱ Exploring: <strong>{total_visit // 60}h {total_visit % 60:02d}min</strong>
          ({len(day.attractions)} attractions){drive_note}
        </p>"""

    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#1e293b;max-width:700px;margin:auto;padding:24px;">
      <h1 style="color:#2563eb;">✈️ Custom Trip Advisor</h1>
      <h2 style="margin-top:0;">{itinerary.destination}</h2>
      <p style="color:#64748b;">
        📅 {itinerary.start_date} → {itinerary.end_date} &nbsp;·&nbsp; {itinerary.total_days} days
      </p>
      <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;">
      {days_html}
      <hr style="border:none;border-top:1px solid #e2e8f0;margin:28px 0 16px;">
      <p style="font-size:12px;color:#94a3b8;">Generated by Custom Trip Advisor · Powered by CrewAI</p>
    </body></html>"""


def send_itinerary_email(to_address: str, itinerary: Itinerary, routes: dict) -> tuple[bool, str]:
    """Send the itinerary via Resend. Returns (success, error_message)."""
    if not RESEND_API_KEY:
        return False, "RESEND_API_KEY not set in .env"
    if not EMAIL_SENDER:
        return False, "EMAIL_SENDER not set in .env"

    resend.api_key = RESEND_API_KEY

    try:
        resend.Emails.send({
            "from": f"Custom Trip Advisor <{EMAIL_SENDER}>",
            "to": [to_address],
            "subject": f"Your {itinerary.total_days}-day trip to {itinerary.destination}",
            "html": _build_html(itinerary, routes),
        })
        return True, ""
    except Exception as e:
        return False, str(e)
